name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 graphql_api python_service db_migration observability --max-line-length=79 --count --extend-ignore=E203

      - name: Run unit tests
        run: |
          pytest

      - name: Verify migration script runs
        run: |
          python db_migration/migrate.py

      - name: Start observability metrics (demo)
        run: |
          python observability/logging_config.py &
          sleep 5
          curl http://localhost:8001/metrics || echo "Metrics not reachable (demo run)"
